ALTER TABLE "User" ADD COLUMN "pushTaskAssigned" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "pushTaskOverdue" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "pushAnnouncements" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "pushDailyAppointments" BOOLEAN NOT NULL DEFAULT false;
